### ISSUE TITLE
[prometheus-to-sd] Resource types: None

### ISSUE THREAD

**Issue by martynasb** [GoogleCloudPlatform/k8s-stackdriver#153] opened 2018-05-09 11:18 UTC
I am running the `prometheus-to-sd` sidecar that scrapes the Prometheus metrics endpoint of my service and sends metrics to Stackdriver. There is a metric called `handler_error_count` which represents API handler errors, e.g.:

```
handler_error_count{caller="some_caller",error_type="client",outcome="invalid_argument",procedure="some_procedure"} 1
```

I can find the metric in Stackdriver's Metrics Explorer but it says that its resource type is `None`. For this reason I am unable to create charts or set up alert policies using this metric.

Unless I am missing something, the resource type should be [`gke_container`](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/translator/translator.go#L168) for all metrics.

Any suggestions on how to fix this issue would be appreciated.

**Comment by martynasb** [comment] 2018-05-09 12:49
I've verified that the `SendToStackdriver` function does indeed send the resource type. Looks like there is an issue with Stackdriver.

**Comment by martynasb** [comment] 2018-05-10 13:19
Deleting the metric and restarting prometheus-to-sd fixed this. I am unable to reproduce the issue though.

**Comment by x13n** [comment] 2018-05-18 09:34
Since you're unable to reproduce, I'm closing this. Please let us know if this happens again (and is reproducible).

**Closed by x13n** 2018-05-18 09:34 UTC
